cmd/jupyter流式播放代码；add stream display example in cmd/jupyter mode
2noise/ChatTTS pull request #512
Opened 2024-07-03 03:20 UTC by ZaymeShaw

The project currently supports streaming generation, but there is no streaming display case, so i add a new example supporting streaming display in cmd/jupyter mode.It internally implemented a write thread and a read thread for inference and audio playback at the same time, which is relatively simple for users to use
项目当前已支持流式生成，但是没有流式播放的案例，所以新增了一个支持cmd/jupyter模式下实现流式播放的例子。内部实现了一个写线程和读线程同时进行推理和音频播放，用户使用起来比较简单
#180 #125

2024-07-03 04:26 UTC, fumiama requested changes
Thanks!

文件可简单命名为`stream.py`

2024-07-03 04:26 UTC, fumiama commented on examples/cmd/stream_display.py
> +import pyaudio
应在requirements.txt加入相关依赖。

2024-07-03 04:26 UTC, fumiama commented on examples/cmd/stream_display.py
> +            waveform=(new_wave*32767).astype(np.int16)
可使用防爆音的`tools.audio.unsafe_float_to_int16`

2024-07-03 04:26 UTC, fumiama commented on examples/cmd/stream_display.py
> +            write_binary = struct.pack('<' + 'h' * len(waveform), *waveform)
效率太低，建议用
```py
waveform.astype("<i2").tobytes()
```

2024-07-03 04:26 UTC, fumiama commented on examples/cmd/stream_display.py
> +class ChatTTSstreamer:
可省略前缀`TTS`，直接命名为`ChatStreamer`。

2024-07-03 04:26 UTC, fumiama commented on examples/cmd/stream_display.py
> +    def play_article(self,waittime_tostart=30):
名字直接`play`即可。

2024-07-03 04:26 UTC, fumiama commented on examples/cmd/stream_display.py
> +    streamer=ChatTTSstreamer()
建议将此方法包装入streamer，可命名为`start`，同时提供对应join。

2024-07-03 04:26 UTC, fumiama commented on examples/cmd/stream_display.py
> +    Audio(complete_waveform[0], rate=24_000, autoplay=True)
既然已经流式，可不必播放完整声音。

2024-07-03 05:34 UTC, ZaymeShaw commented on examples/cmd/stream_display.py
> +            waveform=(new_wave*32767).astype(np.int16)
感谢建议！

2024-07-04 08:52 UTC, ZaymeShaw commented
我发现一个问题，stream infer的generator正常生成的是12032维的ndarray列表，但有小概率会在中间变成256维ndarray列表，256维部分的声音全是噪声，这个应该不是我的流式播放处理逻辑导致的问题。我尝试把流式输出全部先取出来再播放，256维部分也是噪声。大概每运行10几次streamchat左右会出现一次这个问题

2024-07-04 10:19 UTC, fumiama commented
> 我发现一个问题，stream infer的generator正常生成的是12032维的ndarray列表，但有小概率会在中间变成256维ndarray列表，256维部分的声音全是噪声

可以开一个issue，这应该是流式自己的问题。

2024-07-04 10:21 UTC, fumiama approved these changes
Thanks!

2024-07-04 10:21 UTC, merged