Add scripts to support onnx export
2noise/ChatTTS pull request #622
Opened 2024-07-23 10:01 UTC by ZillaRU

看到Issue里有人需要onnx导出的方案，来共享下之前写的onnx 导出脚本。cpp部署部分由于硬件加速api不通用，暂时没有放上来。

2024-07-23 15:19 UTC, fumiama requested changes
推荐放置在`tools`

2024-07-23 15:19 UTC, fumiama commented on onnx_export/README.md
> +2. Replace `modeling_llama.py` with `./onnx_export/assets/modeling_llama.py`.
为什么需要侵入式修改？如无法避免，建议自建仓库，然后由 @libukai 收录到 [Awesome-ChatTTS](https://github.com/libukai/Awesome-ChatTTS)

2024-07-24 03:10 UTC, ZillaRU commented on onnx_export/README.md
> +2. Replace `modeling_llama.py` with `./onnx_export/assets/modeling_llama.py`.
ok 我参考下tools。直接加一个用于转换的gpt.py实现在tools下面，这样可以接受吗？

2024-07-24 07:22 UTC, fumiama commented on onnx_export/README.md
> +2. Replace `modeling_llama.py` with `./onnx_export/assets/modeling_llama.py`.
只要你不动用户已经安装的库，怎么样搞无所谓。侵入式修改库是很危险的行为，不是官方库应当提倡的。

2024-07-28 15:53 UTC, fumiama reviewed
可直接命名为`tools/onnx`

2024-07-28 15:54 UTC, fumiama commented
我又想了一下，还是放`examples`比较好，`examples/onnx`

2024-07-29 05:23 UTC, fumiama approved these changes

2024-07-29 12:48 UTC, ZillaRU commented
😂卡在了自动检查，setuptools出错

2024-07-29 16:55 UTC, fumiama commented
OK了，他有的时候抽风，需要重新运行一下。

2024-07-29 16:55 UTC, merged