docs: add README.kr
2noise/ChatTTS pull request #778
Opened 2024-10-10 13:10 UTC by pengooseDev

### Description

- Added README.md(KR)
- Added links to KR Docs

Always grateful for the Amazing projects and for the updates. :)

2024-10-15 15:00 UTC, fumiama requested changes
Thanks!

2024-10-15 15:00 UTC, fumiama commented on README.md
> +**English** | [**简体中文**](docs/cn/README.md) | [**日本語**](docs/jp/README.md) | [**Русский**](docs/ru/README.md) | [**Español**](docs/es/README.md) | [**Français**](docs/fr/README.md) | [**한국어**](../kr/
```suggestion
**English** | [**简体中文**](docs/cn/README.md) | [**日本語**](docs/jp/README.md) | [**Русский**](docs/ru/README.md) | [**Español**](docs/es/README.md) | [**Français**](docs/fr/README.md) | [**한국어**](docs/kr/README.md)
```

2024-10-15 22:17 UTC, pengooseDev commented
@fumiama The request has been applied! Thx :)

2024-10-16 03:25 UTC, fumiama approved these changes

2024-10-16 03:25 UTC, merged