Fix for Ascend NPU when using ChatTTS to sample the voice of a real speaker
2noise/ChatTTS pull request #788
Opened 2024-10-16 13:46 UTC by shen-shanshan

# What does this PR do?

## Overview

This PR is a bugfix for Ascend NPU when using ChatTTS to sample the voice of a real speaker.

## Environment

- OS: ubuntu 20.04
- NPU: Atlas 300T A2
- CANN: 8.0.RC2
- torch-npu: 2.1.0.post6
- torch: 2.1.0

## Problem

Complex dtype used in the process of computing MelSpectrogram is not supported in `torch_npu` now, and we could get a error when sampling the voice of a real speaker.

![bug_1](https://github.com/user-attachments/assets/002bbb64-fd2a-40e7-8755-e74bc96dadb1)

The logs are showed below:

```bash
[+0000 20241016 12:19:06] [WARN]  WebUI  | funcs | no ffmpeg installed, use wav file output
[+0000 20241016 12:19:06] [INFO]  WebUI  | webui | loading ChatTTS model...
[+0000 20241016 12:19:06] [INFO] ChatTTS | dl | checking assets...
/home/sss/bin/miniconda/miniconda3/envs/chattts_2/lib/python3.10/site-packages/gradio/analytics.py:106: UserWarning: IMPORTANT: You are using gradio version 4.44.0, however version 5.0.1 is available, please upgrade. 
--------
  warnings.warn(
[+0000 20241016 12:19:10] [INFO] ChatTTS | dl | all assets are already latest.
[W compiler_depend.ts:623] Warning: expandable_segments currently defaults to false. You can enable this feature by `export PYTORCH_NPU_ALLOC_CONF = expandable_segments:True`. (function operator())
[+0000 20241016 12:19:16] [INFO] ChatTTS | core | use device npu:0
/home/sss/bin/miniconda/miniconda3/envs/chattts_2/lib/python3.10/site-packages/torch/_utils.py:831: UserWarning: TypedStorage is deprecated. It will be removed in the future and UntypedStorage will be the only storage class. This should only matter to you if you are using storages directly.  To access UntypedStorage directly, use tensor.untyped_storage() instead of tensor.storage()
  return self.fget.__get__(instance, owner)()
[+0000 20241016 12:19:17] [INFO] ChatTTS | core | vocos loaded.
[+0000 20241016 12:19:17] [INFO] ChatTTS | core | dvae loaded.
[+0000 20241016 12:19:18] [INFO] ChatTTS | core | embed loaded.
[+0000 20241016 12:19:18] [INFO] ChatTTS | core | gpt loaded.
[+0000 20241016 12:19:18] [INFO] ChatTTS | core | speaker loaded.
[+0000 20241016 12:19:18] [INFO] ChatTTS | core | decoder loaded.
[+0000 20241016 12:19:18] [INFO] ChatTTS | core | tokenizer loaded.
[+0000 20241016 12:19:18] [WARN]  WebUI  | funcs | Package nemo_text_processing not found!
[+0000 20241016 12:19:18] [WARN]  WebUI  | funcs | Run: conda install -c conda-forge pynini=2.1.5 && pip install nemo_text_processing
[+0000 20241016 12:19:18] [WARN]  WebUI  | funcs | Package WeTextProcessing not found!
[+0000 20241016 12:19:18] [WARN]  WebUI  | funcs | Run: conda install -c conda-forge pynini=2.1.5 && pip install WeTextProcessing
[+0000 20241016 12:19:18] [INFO]  WebUI  | webui | Models loaded successfully.
Running on local URL:  http://0.0.0.0:8080

To create a public link, set `share=True` in `launch()`.
Traceback (most recent call last):
  File "/home/sss/bin/miniconda/miniconda3/envs/chattts_2/lib/python3.10/site-packages/gradio/queueing.py", line 536, in process_events
    response = await route_utils.call_process_api(
  File "/home/sss/bin/miniconda/miniconda3/envs/chattts_2/lib/python3.10/site-packages/gradio/route_utils.py", line 322, in call_process_api
    output = await app.get_blocks().process_api(
  File "/home/sss/bin/miniconda/miniconda3/envs/chattts_2/lib/python3.10/site-packages/gradio/blocks.py", line 1935, in process_api
    result = await self.call_function(
  File "/home/sss/bin/miniconda/miniconda3/envs/chattts_2/lib/python3.10/site-packages/gradio/blocks.py", line 1520, in call_function
    prediction = await anyio.to_thread.run_sync(  # type: ignore
  File "/home/sss/bin/miniconda/miniconda3/envs/chattts_2/lib/python3.10/site-packages/anyio/to_thread.py", line 56, in run_sync
    return await get_async_backend().run_sync_in_worker_thread(
  File "/home/sss/bin/miniconda/miniconda3/envs/chattts_2/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 2405, in run_sync_in_worker_thread
    return await future
  File "/home/sss/bin/miniconda/miniconda3/envs/chattts_2/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 914, in run
    result = context.run(func, *args)
  File "/home/sss/bin/miniconda/miniconda3/envs/chattts_2/lib/python3.10/site-packages/gradio/utils.py", line 826, in wrapper
    response = f(*args, **kwargs)
  File "/home/sss/github/ChatTTS/examples/web/funcs.py", line 118, in on_upload_sample_audio
    spk_smp = chat.sample_audio_speaker(sample_audio)
  File "/home/sss/github/ChatTTS/ChatTTS/core.py", line 163, in sample_audio_speaker
    return self.speaker.encode_prompt(self.dvae.sample_audio(wav))
  File "/home/sss/bin/miniconda/miniconda3/envs/chattts_2/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/home/sss/github/ChatTTS/ChatTTS/model/dvae.py", line 296, in sample_audio
    return self(wav, "encode").squeeze_(0)
  File "/home/sss/github/ChatTTS/ChatTTS/model/dvae.py", line 252, in __call__
    return super().__call__(inp, mode)
  File "/home/sss/bin/miniconda/miniconda3/envs/chattts_2/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/sss/bin/miniconda/miniconda3/envs/chattts_2/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/sss/bin/miniconda/miniconda3/envs/chattts_2/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/home/sss/github/ChatTTS/ChatTTS/model/dvae.py", line 259, in forward
    mel = self.preprocessor_mel(inp)
  File "/home/sss/github/ChatTTS/ChatTTS/model/dvae.py", line 199, in __call__
    return super().__call__(audio)
  File "/home/sss/bin/miniconda/miniconda3/envs/chattts_2/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/sss/bin/miniconda/miniconda3/envs/chattts_2/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/sss/github/ChatTTS/ChatTTS/model/dvae.py", line 203, in forward
    mel: torch.Tensor = self.mel_spec(audio)
  File "/home/sss/bin/miniconda/miniconda3/envs/chattts_2/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/sss/bin/miniconda/miniconda3/envs/chattts_2/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/sss/bin/miniconda/miniconda3/envs/chattts_2/lib/python3.10/site-packages/torchaudio/transforms/_transforms.py", line 619, in forward
    specgram = self.spectrogram(waveform)
  File "/home/sss/bin/miniconda/miniconda3/envs/chattts_2/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/sss/bin/miniconda/miniconda3/envs/chattts_2/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/sss/bin/miniconda/miniconda3/envs/chattts_2/lib/python3.10/site-packages/torchaudio/transforms/_transforms.py", line 110, in forward
    return F.spectrogram(
  File "/home/sss/bin/miniconda/miniconda3/envs/chattts_2/lib/python3.10/site-packages/torchaudio/functional/functional.py", line 146, in spectrogram
    return spec_f.abs()
RuntimeError: call aclnnAbs failed, detail:EZ1001: [PID: 271329] 2024-10-16-12:19:57.030.507 self not implemented for DT_COMPLEX64, should be in dtype support list [DT_DOUBLE,DT_FLOAT,DT_FLOAT16,DT_INT64,DT_INT32,DT_INT16,DT_INT8,DT_UINT8,DT_BOOL,DT_BFLOAT16,].
```

## Solution

Therefore, we put this audio data and MelSpectrogram network o [...]

2024-10-17 17:17 UTC, fumiama commented on ChatTTS/model/dvae.py
> +        if "npu" in str(self.device):
DVAE即使全部用CPU也并不会占用很长的处理时间，考虑将整个模型先切换到CPU，待`torchaudio.transforms.MelSpectrogram`适配完成后切回。

2024-10-18 06:36 UTC, shen-shanshan commented on ChatTTS/model/dvae.py
> +        if "npu" in str(self.device):
已修改😄， @fumiama

2024-10-18 06:40 UTC, shen-shanshan commented on ChatTTS/model/dvae.py
> +        if "npu" in str(self.device):
另外反馈一个问题，我看 `dev` 分支尝试加载模型失败，显示找不到 `Vocos.safetensors`、`DVAE.safetensors` 等模型文件，我看 HF 上也没有这些文件，导致 CI 报错。

2024-10-18 07:11 UTC, fumiama commented on ChatTTS/model/dvae.py
> +        if "npu" in str(self.device):
HF的最新模型还没有合，测试可以下载https://huggingface.co/2Noise/ChatTTS/discussions/33

2024-10-18 07:15 UTC, fumiama requested changes

2024-10-18 07:15 UTC, fumiama commented on ChatTTS/core.py
> +            .to(dvae_device)
最新代码的写法已更改，应当使用最新写法`load_pretrained`。

2024-10-18 07:15 UTC, fumiama commented on ChatTTS/core.py
> +        sample_audio = self.dvae.sample_audio(wav)
这里不必更改。

2024-10-21 02:59 UTC, shen-shanshan commented
已修改😄， @fumiama

2024-10-21 06:56 UTC, fumiama approved these changes
Thanks!

2024-10-21 06:57 UTC, merged