add cache_dir parameter
2noise/ChatTTS pull request #863
Opened 2024-12-31 02:15 UTC by BBC-Esq

Currently, it's the program only allows you to use "huggingface," "local," or "custom" but none allow you to specify a directory where you want to download a file automatically using ```snapshot_download."  This fixes that.

This pull request implements the following:

Here's a brief summary of the different options for handling model files in ChatTTS:

`source="huggingface"`: Downloads models from HuggingFace repo to ~/.cache/huggingface
  * or to cache_dir if specified

`source="local"`: Downloads models from HuggingFace repo to current working directory
  * or to cache_dir if specified

`source="custom"`:
  * No change

## Example Usage:

```python
from ChatTTS import Chat

# Option 1: Using huggingface source with custom cache directory
chat = Chat()
chat.load(
    source="huggingface",
    cache_dir="path/to/your/models",
    device="cuda"
)

# Option 2: Using local source with custom cache directory 
chat = Chat()
chat.load(
    source="local",
    cache_dir="path/to/your/models",
    device="cuda"
)

# Original behavior still works without cache_dir
chat = Chat()
chat.load(
    source="huggingface",  # Will use ~/.cache/huggingface
    device="cuda"
)
```

2025-01-07 11:00 UTC, fumiama requested changes
Thanks!

2025-01-07 11:02 UTC, fumiama reviewed
And you should choose which one you want to merge. #864 or this?

2025-01-07 11:53 UTC, fumiama approved these changes

2025-01-07 11:53 UTC, merged

2025-01-18 15:53 UTC, BBC-Esq commented
Feel free to delete the other pull request, although I do think that one is superior.

2025-01-19 12:27 UTC, fumiama commented
> Feel free to delete the other pull request, although I do think that one is superior.

Well, you can edit them to resolve the conflict and I will still review it.